language: php
php:
  - "hhvm"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script: "phpunit --configuration phpunit.xml.dist"
